[project]
name = "mkdocs_simple_blog"
version = "0.3.0.dev1"
authors = [
  { name="Fernando Celmer", email="email@fernandocelmer.com" },
]
license = {file = "LICENSE"}
description = "Mkdocs Blog Theme"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
	"mkdocs"
]
classifiers = [
  'Development Status :: 4 - Beta',
  "Operating System :: OS Independent",
  'Intended Audience :: Developers',
  'Natural Language :: English',
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

[project.urls]
Homepage = "https://github.com/FernandoCelmer/mkdocs-simple-blog"
Issues = "https://github.com/FernandoCelmer/mkdocs-simple-blog/issues"
Repository = "https://github.com/FernandoCelmer/mkdocs-simple-blog"
Documentation = "https://github.com/FernandoCelmer/mkdocs-simple-blog/blob/master/README.md"

[tool.poetry]
name = "mkdocs_simple_blog"
version = "0.3.0.dev1"
description = "Mkdocs Blog Theme"
authors = ["Fernando Celmer <email@fernandocelmer.com>"]
readme = "README.md"
license = "MIT"
package-mode = true
homepage = "https://github.com/FernandoCelmer/mkdocs-simple-blog"
documentation = "https://fernandocelmer.github.io/mkdocs-simple-blog/"
repository = "https://github.com/FernandoCelmer/mkdocs-simple-blog"
classifiers = [
  'Development Status :: 5 - Production/Stable',
  "Operating System :: OS Independent",
  'Intended Audience :: Developers',
  'Natural Language :: English',
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

[tool.poetry.dependencies]
python = ">=3.9.0"
mkdocs = "^1.6.1"

[tool.poetry.group.dev.dependencies]
build = "^1.2.2.post1"

[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
