site_name: MkDocs Simple Blog
repo_name: FernandoCelmer/mkdocs-simple-blog
repo_url: https://github.com/FernandoCelmer/mkdocs-simple-blog
site_url: https://www.fernandocelmer.com/
copyright: Fernando Celmer

nav:
    - Home: index.md
    - Getting Started: nav/getting-started.md
    - Setup:
      - nav/setup/colors.md
      - nav/setup/fonts.md
      - nav/setup/logo.md
      - nav/setup/favicon.md
    - Development:
      - nav/development/development-guide.md
      - nav/development/release-notes.md

theme:
  name: simple-blog
  theme_style: light
  title_style: normal
  favicon: assets/favicon.ico
  logo: assets/logo.png
  # colors:
  #   text: black
  #   title: black
  #   primary: black
  #   background: white
